allow custom filenaming
adafruit/Adafruit_CircuitPython_PyCamera pull request #32
Opened 2024-02-25 15:31 UTC by FoamyGuy

This change allows you to pass a custom string to get used instead of the default "img" in the photo filenames. 

It will still include the 4 digit integer counter for ensuring unique names. 

resolves #17

2024-03-04 18:13 UTC, jepler requested changes
Thank you! However, I have a quibble

2024-03-04 21:06 UTC, FoamyGuy commented on adafruit_pycamera/__init__.py
> +            )
The latest commits change that to use a single format operation. It turns out my IDEs code formatter also unintentionally broke the example by splitting a long line string across multiples so I fixed that with `.format()`

2024-03-05 14:22 UTC, FoamyGuy commented on adafruit_pycamera/__init__.py
> +            filename = f"/sd/{filename_prefix}{self._image_counter}.{extension}"
whoops, thank you. will commit that today.

2024-03-05 17:27 UTC, FoamyGuy commented on adafruit_pycamera/__init__.py
> +            filename = f"/sd/{filename_prefix}{self._image_counter}.{extension}"
That change has been made now.

2025-01-16 21:41 UTC, merged